# Generated by Django 4.0.3 on 2022-03-18 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoEletrInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.CharField(max_length=255)),
                ('url_produto', models.TextField()),
                ('plataforma', models.CharField(max_length=100, verbose_name='website')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('monitorar', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='PrecoInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=50, verbose_name='Preço do produto')),
                ('data_preco', models.DateTimeField(auto_now_add=True, verbose_name='Data do preço')),
                ('produto_referencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produtoeletrinf', verbose_name='Produto referente')),
            ],
            options={
                'db_table': 'preco_produto',
            },
        ),
    ]
