# Generated by Django 4.0.3 on 2022-03-20 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtoeletrinf',
            name='perc_desconto',
            field=models.FloatField(blank=True, null=True, verbose_name='Porcentagem Desconto'),
        ),
        migrations.AddField(
            model_name='produtoeletrinf',
            name='tem_estoque',
            field=models.BooleanField(default=True, verbose_name='Estoque disponível'),
        ),
        migrations.AlterField(
            model_name='produtoeletrinf',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='produtoeletrinf',
            name='monitorar',
            field=models.BooleanField(default=True, verbose_name='Monitorar'),
        ),
        migrations.AlterField(
            model_name='produtoeletrinf',
            name='plataforma',
            field=models.CharField(max_length=100, verbose_name='Site'),
        ),
    ]
