# Generated by Django 4.0.3 on 2022-03-22 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_produtoeletrinf_perc_desconto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoeletrinf',
            name='nome',
            field=models.TextField(),
        ),
    ]
