# Generated by Django 4.0.3 on 2022-03-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produtoeletrinf_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoeletrinf',
            name='imagem',
            field=models.TextField(),
        ),
    ]
